apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geth-devnet.fullname" . }}
  labels:
    {{- include "geth-devnet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "geth-devnet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "geth-devnet.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: geth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - geth
            - --dev
            - --http
            - --http.addr=0.0.0.0
            - --http.api=eth,net,web3,txpool,debug
            - --ws
            - --ws.addr=0.0.0.0
          ports:
            - name: http
              containerPort: 8545
            - name: ws
              containerPort: 8546
