apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geth-devnet.fullname" . }}
  labels:
    app: geth-devnet
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: geth-devnet
  template:
    metadata:
      labels:
        app: geth-devnet
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: geth
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: rpc
              containerPort: 8545
          command:
            - geth
          args:
            - "--dev"
            - "--http"
            - "--http.addr=0.0.0.0"
            - "--http.api=eth,net,web3,txpool,debug"
            - "--allow-insecure-unlock"
            - "--http.corsdomain=*"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
