apiVersion: v1
kind: Service
metadata:
  name: geth-devnet-svc
  labels:
    app: geth-devnet
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rpc
  selector:
    app: geth-devnet
